"""
 Standard Django app config file.  We don't really need anything here.
"""
from django.apps import AppConfig


class TicketsConfig(AppConfig):
    """
     Autogenerated by Django
    """
    name = 'tickets'
